LAB/urls.py
# include PARA INCLUIR OS OUTROS ARQUIVOS urls.py PARA ESSE ARQUIVO
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # ENTRAR NO MODO ADMINSTRATIVO DO SISTEMA
    url(r'^admin/', admin.site.urls),

    # ROTAS PARA O APP USER (login, logout, cadastro de novo user)
    url(r'^', include('user.urls', namespace='usuario', app_name='user')),

    # ROTAS PARA O APP marcacaoLaboratorio (cadastro, editar, excluir e ver todas marcacao)
    url(r'^marcacaoLaboratorio', include('marcacaoLaboratorio.urls', namespace='marcacaoLaboratorio', app_name='marcacaoLaboratorio')),

    # ROTAS PARA O APP laboratorio (cadastro, editar, excluir e ver todas marcacao)
    url(r'^laboratorio', include('laboratorio.urls', namespace='laboratorio', app_name='laboratorio')),
]

marcacaoLaboratorio/urls.py
# importa url do DJANGO
from django.conf.urls import url
# importa todas as views
from . import views

urlpatterns = [
    # manda para a indexLaboratorio no arquivo views.py
    url(r'^$', views.do_index, name='indexMarcacao'),

    # manda para a indexLaboratorio no arquivo views.py
    url(r'^cadastrar$', views.cadastrarMarcacao, name='novoMarcacao'),

    # manda para a indexLaboratorio no arquivo views.py
    url(r'^editar/(?P<id>\d+)/$', views.editarMarcacao, name='editarMarcacao'),

    # manda para a indexLaboratorio no arquivo views.py
    url(r'^excluir/(?P<id>\d+)/$', views.excluirMarcacao, name='excluirMarcacao'),
]

marcacaoLaboratorio/models.py
# importando o models no DJANGO
from django.db import models
# imporatando model user do DJANGO
from django.contrib.auth.models import User
# importando do APP laboratorio ( laboratorio/models.py)
from laboratorio.models import Laboratorio

class Marcacao(models.Model): # nome da tabela que sera criado no banco de dados

    cod_laboratorio = models.ForeignKey(Laboratorio, on_delete=models.CASCADE) # nome da coluna, tipo e tamanho maximo
    cod_user = models.ForeignKey(User, on_delete=models.CASCADE) # nome da coluna, tipo e tamanho maximo
    data_marcacao = models.DateTimeField() # nome da coluna, tipo e tamanho maximo
    hora = models.TimeField() # nome da coluna, tipo e tamanho maximo
    data = models.DateField() # nome da coluna, tipo e tamanho maximo

    # funcao de retorno quando se faz um SELECT
    def __str__(self):
        return self.data_marcacao # por DEFAULT vem o data_marcacao

    #   O CREATE GERADO SERA ESSE
    """
    CREATE TABLE marcacaoLaboratorio_marcacao
         (
            id integer PRIMARY KEY AUTOINCREMENT,
            cod_laboratorio INT(4) NOT NULL,
            cod_user INT(4) NOT NULL,
            data_marcacao DATETIME,
            hora DATE ,
            data TIME ,
            FOREIGN KEY (cod_laboratorio) references laboratorio_laboratorio(id),
            FOREIGN KEY (cod_user) references auth_user(id),
         );
    """

marcacaoLaboratorio/forms.py
#-*- coding:utf-8 -*-

# importa ModelForms do DJANGO
from django.forms import ModelForm
# importa o form do DJANGO
from django import forms
# importa a models Marcacao (model.py)
from marcacaoLaboratorio.models import Marcacao
# importa datetime do PYTHON
from datetime import datetime

class MarcacaoForm(ModelForm):

    class Meta:
        model = Marcacao # nome da MODEL

        # nome das colunas que sera criado o formulario
        fields = ['cod_laboratorio', 'hora', 'data', 'data_marcacao', 'cod_user']
        cod_laboratorio = forms.Select(choices=fields)
        widgets = {
            # estilizando o form
            'cod_laboratorio': forms.Select(attrs={'class':'form-control'}),
            'hora':forms.TimeInput(attrs={'class':'form-control', 'type':'time'}),
            'data':forms.DateInput(attrs={'class':'form-control', 'type': 'date'}),
            'data_marcacao':forms.TextInput(attrs={'class':'form-control', 'type': 'hidden', 'value': datetime.now()}),
        }

marcacaoLaboratorio/views.py
# importando o render (renderizar pagina) e redirect (redirecionar pagina)
from django.shortcuts import render, redirect
# importando login_required (para verificar se o usuario esta logado)
from django.contrib.auth.decorators import login_required
# importando a model Marcacao
from marcacaoLaboratorio.models import Marcacao
#importando o formulario LaboratorioForm
from marcacaoLaboratorio.forms import MarcacaoForm

"""
@login_required verifica se o usuario esta logado 
caso sim entra na funcao se não estiver logado 
ele manda para a raiz do projeto
(FOI DEFINIDO QUE IRA MANDAR PARA A RAIZ DO PROJETO 
    NO ARQUIVO settings.py linha 139 - LOGIN_URL = '/' )
"""
@login_required
def do_index(request):
    # lista todos os Marcacao com ordem do id
    lista = Marcacao.objects.all().order_by('-id')

    # transforma a busca em um JSON para mandar para o HTML
    context = {
        'lista_marcacao': lista
    }

    return render(request, 'marcacao/index.html', context)

@login_required
def cadastrarMarcacao(request):

    formulario = MarcacaoForm(request.POST or None)

    # transformao formulario em um JSON para mandar para o HTML
    context = {
        'form': formulario
    }

    # verifica se o metodo é do tipo POST
    if request.method == 'POST':
        formulario.cod_user = request.user

        # verifica se o formulario esta valido de acordo com o arquivo forms.py
        if formulario.is_valid():
            formulario.cod_user = request.user

            # salva os dados do formulario no banco de dados
            formulario.save()

            # redireciona para a rota '/marcacaoLaboratorio'
            return redirect('/marcacaoLaboratorio')
    # renderiza o html com o mandando o JSON como parametro
    return render(request, 'marcacao/novo.html', context)

@login_required
def editarMarcacao(request, id):
    # lista todos os Marcacao com ordem do id
    marcacao = Marcacao.objects.get(id=id)

    # adciona os dados do banco de dados no formulario definido con forms.py
    formulario = MarcacaoForm(request.POST or None, instance=marcacao)
    # transforma o formulario em um JSON para mandar para o HTML

    context = {
        'form': formulario
    }

    # verifica se o metodo é do tipo POST
    if request.method == 'POST':
        # verifica se o formulario esta valido de acordo com o arquivo forms.py

        if formulario.is_valid():
            v = formulario.save(commit=False)
            v.cod_user = request.user

            # salva os dados do formulario no banco de dados
            formulario.save()

            # redireciona para a rota '/marcacaoLaboratorio'
            return redirect('/marcacaoLaboratorio')

    # renderiza o html com o mandando o JSON como parametro
    return render(request, 'marcacao/novo.html', context)

@login_required
def excluirMarcacao(request, id):
    # lista todos os Marcacao com ordem do id
    marcacao = Marcacao.objects.get(id=id)

    # deleta o dado que veio na busca
    marcacao.delete()
    # redireciona para a rota '/marcacaoLaboratorio'
    return redirect('/marcacaoLaboratorio')

marcacaoLaboratorio/templates/marcacao/index.html
{% include 'template.html' %}
{% block conteudo %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
     <h1 class="page-header">Tabela de Marcação</h1>

            <a href="{% url 'marcacaoLaboratorio:novoMarcacao' %}" class="btn btn-success">Adcionar</a>

          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Nome Laboratorio</th>
                  <th>Professor</th>
                  <th>Data Marcada</th>
                  <th>Hora Marcada</th>
                  <th>Ação</th>
                </tr>
              </thead>
              <tbody>
            {% for lista in lista_marcacao %}

               <tr>
                  <td>{{ lista.cod_laboratorio }}</td>
                  <td>{{ lista.cod_user.first_name }}</td>
                  <td>{{ lista.data }}</td>
                  <td>{{ lista.hora }}</td>

                  <td>
                      {% if lista.cod_user.id == user.id %}
                          <a href="{% url 'marcacaoLaboratorio:editarMarcacao' lista.id %}" class="btn btn-primary">Editar</a>
                          <a href="{% url 'marcacaoLaboratorio:excluirMarcacao' lista.id %}" class="btn btn-danger">Excluir</a>
                      {% endif %}
                  </td>
               </tr>
            {% endfor %}

              </tbody>
            </table>
          </div>
</div>
{% endblock %}

marcacaoLaboratorio/templates/marcacao/novo.html
{% include 'template.html' %}
{% block conteudo %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
     <h1 class="page-header">Nova Marcacão</h1>

        <form method="post">

        {% csrf_token %}

          <div class="form-group">
              <label for="exampleInputPassword1">Laboratorio</label>
              {{ form.cod_laboratorio }}
          </div>

          <div class="form-group">
            <label for="exampleInputPassword1">Data</label>
            {{ form.data }}
          </div>

          <div class="form-group">
            <label for="exampleInputPassword1">Hora</label>
            {{ form.hora }}
          </div>

            <div class="form-group">

            <input type="hidden" class="form-control" name="cod_user" value="{{ user.id }}">
                {{ form.data_marcacao }}
          </div>

          <button type="submit" class="btn btn-default">Submit</button>
        </form>


    </div>
{% endblock %}