LAB/urls.py
# include PARA INCLUIR OS OUTROS ARQUIVOS urls.py PARA ESSE ARQUIVO
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # ENTRAR NO MODO ADMINSTRATIVO DO SISTEMA
    url(r'^admin/', admin.site.urls),

    # ROTAS PARA O APP USER (login, logout, cadastro de novo user)
    url(r'^', include('user.urls', namespace='usuario', app_name='user')),

    # ROTAS PARA O APP marcacaoLaboratorio (cadastro, editar, excluir e ver todas marcacao)
    url(r'^marcacaoLaboratorio', include('marcacaoLaboratorio.urls', namespace='marcacaoLaboratorio', app_name='marcacaoLaboratorio')),

    # ROTAS PARA O APP laboratorio (cadastro, editar, excluir e ver todas marcacao)
    url(r'^laboratorio', include('laboratorio.urls', namespace='laboratorio', app_name='laboratorio')),
]

user/urls.py
# importa url do DJANGO
from django.conf.urls import url
# importa todas as views
from . import views

urlpatterns = [
    # manda para a indexLaboratorio no arquivo views.py
    url(r'cadastro/$', views.cadastro, name='cadastro'),

    # manda para a indexLaboratorio no arquivo views.py
    url(r'^$', views.do_login, name='login'),

    # manda para a indexLaboratorio no arquivo views.py
    url(r'logout$', views.do_logout, name='logout'),
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
#-*- coding:utf-8 -*-

# importa ModelForms do DJANGO
from django import forms
# importa User do DJANGO
from django.contrib.auth.models import User

class UserModelForm(forms.ModelForm):
    # para a coluna e-mail sempre vim em branco
    User._meta.get_field('email').blank = False

    class Meta:
        model = User # nome da MODEL

        # nome das colunas que sera criado o formulario
        fields = ['username', 'first_name', 'last_name', 'email', 'password']
        widgets = {
            # estilizando o form
            'first_name':forms.TextInput(attrs={'class':'form-control', 'maxlength': '255'}),
            'last_name':forms.TextInput(attrs={'class':'form-control', 'maxlength': 255}),
            'email':forms.EmailInput(attrs={'class':'form-control', 'maxlength': 255}),
            'username':forms.TextInput(attrs={'class':'form-control', 'maxlength': 255}),
            'password':forms.PasswordInput(attrs={'class':'form-control', 'maxlength': 255}),

        }

    # funcao para antes de salvar encriptar a senha
    def save(self, commit=True):
        User = super(UserModelForm, self).save(commit=False)
        User.set_password(self.cleaned_data['password'])
        if commit:
            User.save()
        return User

user/views.py
# importando o render (renderizar pagina) e redirect (redirecionar pagina)
from django.shortcuts import render, redirect
#importando o formulario LaboratorioForm
from user.forms import UserModelForm
"""importando authenticate (autenticar usuarios),
    login (fazer login no sistema),
    logout( fazer logout do sistema)
"""
from django.contrib.auth import authenticate, login ,logout

def cadastro(request):
    form = UserModelForm(request.POST or None)

    # transformao formulario em um JSON para mandar para o HTML
    context = {
        'form':form
    }

    # verifica se o metodo é do tipo POST
    if request.method == 'POST':

        # verifica se o formulario esta valido de acordo com o arquivo forms.py
        if form.is_valid():
            # salva os dados do formulario no banco de dados
            form.save()
            # redireciona para a rota '/' (RAIZ)
            return redirect('/')

    # renderiza o html com o mandando o JSON como parametro
    return render(request, 'user/cadastro.html', context)

def do_login(request):

    # verifica se o metodo é do tipo POST
    if request.method == 'POST':

        #autenticando usuario
        user = authenticate(username=request.POST['username'], password=request.POST['password'])

        #verifica se existe esta existe
        if user is not None:
            #fazendo login e salvando informações do usuario na sessao
            login(request, user)
            # redireciona para a rota '/marcacaoLaboratorio'
            return redirect('/marcacaoLaboratorio')

    # renderiza o html
    return render(request, 'user/login.html')

def do_logout(request):
    #pega tudo que tem na request ( request possui o user da sessao)
    logout(request)
    #redireciona para a raiz
    return redirect('/')

user/templates/user/cadastro.html
{%  include 'head.html' %}
{% block content %}

      <form action="{% url 'usuario:cadastro' %}" class="form-signin" method="post">
        <h2 class="form-signin-heading">Cadastro</h2>

          {% csrf_token %}

          <label>Fisrt Name</label>
          {{ form.first_name }}
          {{ form.first_name.errors }}

          <label>Last Name</label>
          {{ form.last_name }}
          {{ form.last_name.errors }}

          <label>Email</label>
          {{ form.email }}
          {{ form.email.errors }}

          <label>Username</label>
          {{ form.username }}
          {{ form.username.errors }}

          <label>Password</label>
          {{ form.password }}
          {{ form.password.errors }}

        <button class="btn btn-lg btn-primary btn-block" type="submit">Cadastrar</button>
        <a class="btn btn-lg btn-primary btn-block" href="{% url 'usuario:login' %}">Login</a>
      </form>

{% endblock %}

user/templates/user/login.html
{% include 'head.html' %}
{% block content %}

      <form class="form-signin" method="post" action="{% url 'usuario:login' %}">

          <h2 class="form-signin-heading">Login</h2>

          {% csrf_token %}

            <div class="form-group">
                <div class="col-md-12">
                    <input type="text" class="form-control" name="username" placeholder="Login">
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <input type="password" class="form-control" name="password" placeholder="Senha">
                </div>
            </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
        <a href="{% url 'usuario:cadastro' %}" class="btn btn-lg btn-primary btn-block">Cadastrar</a>
      </form>

{% endblock %}