LAB/urls.py
# include PARA INCLUIR OS OUTROS ARQUIVOS urls.py PARA ESSE ARQUIVO
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # ENTRAR NO MODO ADMINSTRATIVO DO SISTEMA
    url(r'^admin/', admin.site.urls),

    # ROTAS PARA O APP USER (login, logout, cadastro de novo user)
    url(r'^', include('user.urls', namespace='usuario', app_name='user')),

    # ROTAS PARA O APP marcacaoLaboratorio (cadastro, editar, excluir e ver todas marcacao)
    url(r'^marcacaoLaboratorio', include('marcacaoLaboratorio.urls', namespace='marcacaoLaboratorio', app_name='marcacaoLaboratorio')),

    # ROTAS PARA O APP laboratorio (cadastro, editar, excluir e ver todas marcacao)
    url(r'^laboratorio', include('laboratorio.urls', namespace='laboratorio', app_name='laboratorio')),
]

laboratorio/urls.py
# importa url do DJANGO
from django.conf.urls import url
# importa todas as views
from . import views

urlpatterns = [
    # manda para a indexLaboratorio no arquivo views.py
    url(r'^$', views.indexLaboratorio, name='indexLaboratorio'),

    # manda para a cadastrarLaboratorio no arquivo views.py
    url(r'^cadastrarLaboratorio$', views.cadastrarLaboratorio, name='novoLaboratorio'),

    # manda para a editarLaboratorio no arquivo views.py
    url(r'^editarLaboratorio/(?P<id>\d+)/$', views.editarLaboratorio, name='editarLaboratorio'),

    # manda para a excluirLaboratorio no arquivo views.py
    url(r'^exluirLaboratorio/(?P<id>\d+)/$', views.excluirLaboratorio, name='excluirLaboratorio'),
]

laboratorio/models.py
# importando o models no DJANGO
from django.db import models

class Laboratorio(models.Model): # nome da tabela que sera criado no banco de dados

    nome_laboratorio = models.CharField(max_length = 100) # nome da coluna, tipo e tamanho maximo
    sigla_laboratorio = models.CharField(max_length= 3) # nome da coluna, tipo e tamanho maximo

    # funcao de retorno quando se faz um SELECT
    def __str__(self):
        return self.nome_laboratorio # por DEFAULT vem o nome_laborario


#   O CREATE GERADO SERA ESSE
    """
    CREATE TABLE laboratorio_laboratorio 
        (
            "id" serial NOT NULL PRIMARY KEY,
            "nome_laboratorio" varchar(100) NOT NULL,
            "sigla_laboratorio" varchar(3) NOT NULL
        );
    
    """

laboratorio/forms.py
#-*- coding:utf-8 -*-

# importa ModelForms do DJANGO
from django.forms import ModelForm
# importa a models laboratorio (model.py)
from laboratorio.models import Laboratorio
# importa o form do DJANGO
from django import forms

class LaboratorioForm(ModelForm):

    class Meta:
        model = Laboratorio # nome da MODEL

        # nome das colunas que sera criado o formulario
        fields = ['nome_laboratorio', 'sigla_laboratorio']
        widgets = {
            # estilizando o form
            'nome_laboratorio':forms.TextInput(attrs={'class':'form-control'}),
            'sigla_laboratorio':forms.TextInput(attrs={'class':'form-control'})
        }

laboratorio/views.py
# importando o render (renderizar pagina) e redirect (redirecionar pagina)
from django.shortcuts import render, redirect
# importando login_required (para verificar se o usuario esta logado)
from django.contrib.auth.decorators import login_required
# importando a model Laboratorio
from laboratorio.models import Laboratorio
#importando o formulario LaboratorioForm
from laboratorio.forms import LaboratorioForm

"""
@login_required verifica se o usuario esta logado 
caso sim entra na funcao se não estiver logado 
ele manda para a raiz do projeto
(FOI DEFINIDO QUE IRA MANDAR PARA A RAIZ DO PROJETO 
    NO ARQUIVO settings.py linha 139 - LOGIN_URL = '/' )
"""
@login_required
def indexLaboratorio(request):
    # lista todos os laboratorio com ordem do id
    lista_laboratorio = Laboratorio.objects.all().order_by('-id')

    # transforma a busca em um JSON para mandar para o HTML
    context = {
        'lista_laboratorio': lista_laboratorio
    }

    # renderiza o html com o mandando o JSON como parametro
    return render(request, 'laboratorio/index.html', context)

@login_required
def cadastrarLaboratorio(request):
    # cria um formulario definodo no arquivo forms.py
    formulario = LaboratorioForm(request.POST or None)

    # transforma o form em um JSON para mandar para o HTML
    context = {
        'form': formulario
    }

    # verifica se o metodo é do tipo POST
    if request.method == 'POST':
        # verifica se o formulario esta valido de acordo com o arquivo forms.py
        if formulario.is_valid():
            # salva os dados do formulario no banco de dados
            formulario.save()
            # redireciona para a rota '/laboratorio'
            return redirect('/laboratorio')

    # renderiza o HTML com o JSON do formulario
    return render(request, 'laboratorio/novo.html', context)

@login_required
def editarLaboratorio(request, id):
    # busca no banco de dados um determinado Laboratorio pelo id
    laboratorio = Laboratorio.objects.get(id=id)

    # adciona os dados do banco de dados no formulario definido con forms.py
    formulario = LaboratorioForm(request.POST or None, instance=laboratorio)

    # transforma o formulario carregado com os dados em um JSON
    context = {
        'form': formulario
    }

    # verifica se o metodo é um POST
    if request.method == 'POST':
        #verifica se o formulario esta valido
        if formulario.is_valid():
            # salva os dados do formulario no banco de dados
            formulario.save()
            # redireciona para a rota '/laboratorio'
            return redirect('/laboratorio')
    # renderiza o HTML com o JSON do formulario
    return render(request, 'laboratorio/novo.html', context)

@login_required
def excluirLaboratorio(request, id):
    # busca no banco de dados um determinado Laboratorio pelo id
    laboratotio = Laboratorio.objects.get(id=id)
    # deleta o dado que veio na busca
    laboratotio.delete()
    # redireciona para a rota '/laboratorio'
    return redirect('/laboratorio')

laboratorio/templates/laboratorio/index.html
{% include 'template.html' %}
{% block conteudo %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
     <h1 class="page-header">Tabela Laboratorio</h1>

            <a href="{% url 'laboratorio:novoLaboratorio' %}" class="btn btn-success">Adcionar</a>

          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Nome Laboratorio</th>
                  <th>Sigla Laboratorio</th>
                  <th>Ação</th>
                </tr>
              </thead>
              <tbody>
            {% for lista in lista_laboratorio %}

               <tr>
                  <td>{{ lista.nome_laboratorio }}</td>
                  <td>{{ lista.sigla_laboratorio }}</td>
                  <td>
                      <a href="{% url 'laboratorio:editarLaboratorio' lista.id %}" class="btn btn-primary">Editar</a>
                      <a href="{% url 'laboratorio:excluirLaboratorio' lista.id %}" class="btn btn-danger">Excluir</a>
                </td>
               </tr>
            {% endfor %}

              </tbody>
            </table>
          </div>
</div>
{% endblock %}

laboratorio/templates/laboratorio/novo.html
{% include 'template.html' %}
{% block conteudo %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
     <h1 class="page-header">Nova Laboratorio</h1>

        <form method="post">

        {% csrf_token %}

          <div class="form-group">
              <label for="exampleInputPassword1">Laboratorio</label>
              {{ form.nome_laboratorio }}
          </div>

          <div class="form-group">
            <label for="exampleInputPassword1">Data</label>
            {{ form.sigla_laboratorio }}
          </div>

          <button type="submit" class="btn btn-default">Submit</button>
        </form>


    </div>
{% endblock %}