LAB/urls.py
# include PARA INCLUIR OS OUTROS ARQUIVOS urls.py PARA ESSE ARQUIVO
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # ENTRAR NO MODO ADMINSTRATIVO DO SISTEMA
    url(r'^admin/', admin.site.urls),

    # ROTAS PARA O APP USER (login, logout, cadastro de novo user)
    url(r'^', include('user.urls', namespace='usuario', app_name='user')),

    # ROTAS PARA O APP marcacaoLaboratorio (cadastro, editar, excluir e ver todas marcacao)
    url(r'^marcacaoLaboratorio', include('marcacaoLaboratorio.urls', namespace='marcacaoLaboratorio', app_name='marcacaoLaboratorio')),

    # ROTAS PARA O APP laboratorio (cadastro, editar, excluir e ver todas marcacao)
    url(r'^laboratorio', include('laboratorio.urls', namespace='laboratorio', app_name='laboratorio')),
]

laboratorio/urls.py
# importa url do DJANGO
from django.conf.urls import url
# importa todas as views
from . import views

urlpatterns = [
    # manda para a indexLaboratorio no arquivo views.py
    url(r'^$', views.indexLaboratorio, name='indexLaboratorio'),

    # manda para a cadastrarLaboratorio no arquivo views.py
    url(r'^cadastrarLaboratorio$', views.cadastrarLaboratorio, name='novoLaboratorio'),

    # manda para a editarLaboratorio no arquivo views.py
    url(r'^editarLaboratorio/(?P<id>\d+)/$', views.editarLaboratorio, name='editarLaboratorio'),

    # manda para a excluirLaboratorio no arquivo views.py
    url(r'^exluirLaboratorio/(?P<id>\d+)/$', views.excluirLaboratorio, name='excluirLaboratorio'),
]

marcacaoLaboratorio/urls.py
# importa url do DJANGO
from django.conf.urls import url
# importa todas as views
from . import views

urlpatterns = [
    # manda para a indexLaboratorio no arquivo views.py
    url(r'^$', views.do_index, name='indexMarcacao'),

    # manda para a indexLaboratorio no arquivo views.py
    url(r'^cadastrar$', views.cadastrarMarcacao, name='novoMarcacao'),

    # manda para a indexLaboratorio no arquivo views.py
    url(r'^editar/(?P<id>\d+)/$', views.editarMarcacao, name='editarMarcacao'),

    # manda para a indexLaboratorio no arquivo views.py
    url(r'^excluir/(?P<id>\d+)/$', views.excluirMarcacao, name='excluirMarcacao'),
]

user/urls.py
# importa url do DJANGO
from django.conf.urls import url
# importa todas as views
from . import views

urlpatterns = [
    # manda para a indexLaboratorio no arquivo views.py
    url(r'cadastro/$', views.cadastro, name='cadastro'),

    # manda para a indexLaboratorio no arquivo views.py
    url(r'^$', views.do_login, name='login'),

    # manda para a indexLaboratorio no arquivo views.py
    url(r'logout$', views.do_logout, name='logout'),
]

templates/head.html
{# para carregar o caminho certo dos css #}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">

  </head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src=" {% static 'bootstrap/js/bootstrap.min.js' %} "></script>

templates/menu.html
<ul class="nav nav-sidebar">
    <li class="active">
        <a href="{% url 'marcacaoLaboratorio:indexMarcacao' %}">
            Home
            <span class="sr-only">(current)</span>
        </a>
    </li>
    <li>
        <a href="{% url 'laboratorio:indexLaboratorio' %}">
            Laboratorio
        </a>
    </li>
</ul>

templates/template.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

  </head>


  <body>

        {#  BARRA DE CIMA #}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'marcacaoLaboratorio:indexMarcacao' %}">UNICEUBx</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a>{{ user.first_name }} {{ user.last_name }}</a></li>
            <li><a href="{% url 'usuario:logout' %}">Sair</a></li>
          </ul>
        </div>
      </div>
    </nav>
        {# FIM BARRA CIMA #}

    <div class="container-fluid">
      <div class="row">

            {#  MENU #}
          <div class="col-sm-3 col-md-2 sidebar">
               {% include 'menu.html' %}
            </div>
            {# FIM MENU #}

            {# CONTEUDO DA PAGINA #}
         {% block conteudo %}
         {% endblock %}
            {# FIM CONTEUDO DA PAGINA #}


      </div>

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src=" {% static 'bootstrap/js/bootstrap.min.js' %} "></script>

  </body>
</html>